version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      # Don't mount these directories to avoid conflicts with container
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/.mypy_cache
      - /app/.uv
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mental_health_db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-for-development}
      - SUPERADMIN_USERNAME=superadmin
      - SUPERADMIN_PASSWORD=super_secure_admin_2024!
      - ADMIN_PANEL_SECRET_KEY=admin_panel_secret_key_2024
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - UV_SYSTEM_PYTHON=1
    depends_on:
      - db
    # Command is overridden by devcontainer.json postStartCommand
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    # Enable for debugging
    stdin_open: true
    tty: true

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mental_health_db
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
