services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "3000:8000"
    volumes:
      - uploads_data:/app/uploads
      - logs_data:/app/logs
      - static_data:/app/static
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-1}@db:5432/mental_health_db
      - SECRET_KEY=${SECRET_KEY}
      - ENV=production
      - CORS_ORIGINS=${CORS_ORIGINS}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      - SMTP_SERVER=${SMTP_SERVER:-smtp.gmail.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME:-}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - EMAIL_FROM=${EMAIL_FROM:-noreply@example.com}
      - FRONTEND_URL=${FRONTEND_URL}
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE:-60}
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-300}
      - WS_MESSAGE_QUEUE_SIZE=${WS_MESSAGE_QUEUE_SIZE:-100}
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE:-10485760}
      - FQDN=${SERVICE_FQDN_API}
      # Logto Authentication Configuration
      - LOGTO_ENDPOINT=${LOGTO_ENDPOINT}
      - LOGTO_APP_ID=${LOGTO_APP_ID}
      - LOGTO_APP_SECRET=${LOGTO_APP_SECRET}
      - LOGTO_MANAGEMENT_APP_ID=${LOGTO_MANAGEMENT_APP_ID}
      - LOGTO_MANAGEMENT_APP_SECRET=${LOGTO_MANAGEMENT_APP_SECRET}
      # Database seeding configuration
      - SEED_DATABASE=${SEED_DATABASE:-false}
      - SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL:-admin@ephra.com}
      - SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD:-}
      - SEED_CARE_PROVIDER_PASSWORD=${SEED_CARE_PROVIDER_PASSWORD:-}
      - SEED_USER_PASSWORD=${SEED_USER_PASSWORD:-}
      - SUPERADMIN_USERNAME=${SUPERADMIN_USERNAME:-superadmin}
      - SUPERADMIN_PASSWORD=${SUPERADMIN_PASSWORD:-super_secure_admin_2024!}
      - MEETING_LINK_BASE_URL=${MEETING_LINK_BASE_URL:-https://meet.jit.si}
      - RUN_MIGRATIONS_ON_STARTUP=${RUN_MIGRATIONS_ON_STARTUP:-true}
      - MAILGUN_API_KEY=${MAILGUN_API_KEY:-}
      - MAILGUN_DOMAIN=${MAILGUN_DOMAIN:-}
      - MAILGUN_BASE_URL=${MAILGUN_BASE_URL:-https://api.eu.mailgun.net/v3}
      - MAILGUN_WEBHOOK_SIGNING_KEY=${MAILGUN_WEBHOOK_SIGNING_KEY:-}
      - APPOINTMENT_REMINDER_TEMPLATE=${APPOINTMENT_REMINDER_TEMPLATE:-15min_before_appointment}
      # Additional Logto Configuration
      - LOGTO_API_RESOURCE=${LOGTO_API_RESOURCE}
      - LOGTO_FE_APP_ID=${LOGTO_FE_APP_ID}
      - LOGTO_POST_LOGOUT_REDIRECT_URI=${LOGTO_POST_LOGOUT_REDIRECT_URI}
      - LOGTO_REDIRECT_URI=${LOGTO_REDIRECT_URI}
      # Role mapping and service configuration
      - ROLES_MAP_STRING=${ROLES_MAP_STRING}
      - SERVICE_URL_API=${SERVICE_URL_API}

    depends_on:
      db:
        condition: service_healthy
    labels:
      - "coolify.managed=true"
      - "traefik.enable=true"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-1}
      - POSTGRES_DB=mental_health_db
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    restart: unless-stopped
    labels:
      - "coolify.managed=true"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"

volumes:
  postgres_data:
    driver: local
  uploads_data:
    driver: local
  logs_data:
    driver: local
  static_data:
    driver: local
