"""Add sleep field to journals

Revision ID: 99fa7d78ce7b
Revises: 2a3665f4be81
Create Date: 2025-05-26 10:12:59.840356

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "99fa7d78ce7b"
down_revision: Union[str, None] = "2a3665f4be81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("journals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sleep", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("journals", schema=None) as batch_op:
        batch_op.drop_column("sleep")

    # ### end Alembic commands ###
