"""Add logto_user_id to users table

Revision ID: bf084bfd940e
Revises: 2dc0873ed09c
Create Date: 2025-06-04 10:06:10.552143

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf084bfd940e"
down_revision: Union[str, None] = "2dc0873ed09c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("logto_user_id", sa.String(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_users_logto_user_id"), ["logto_user_id"], unique=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_logto_user_id"))
        batch_op.drop_column("logto_user_id")

    # ### end Alembic commands ###
