"""updates

Revision ID: af5046959a7d
Revises: add_personal_journal_tables
Create Date: 2025-08-31 20:47:47.423605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5046959a7d'
down_revision: Union[str, None] = 'add_personal_journal_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_message_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email_scheduled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_delivered', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_opened', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('reminder_minutes')
        batch_op.drop_column('email_opened')
        batch_op.drop_column('email_delivered')
        batch_op.drop_column('email_scheduled')
        batch_op.drop_column('email_message_id')

    # ### end Alembic commands ###
